### ISSUE TITLE
Update `About` to read Equinix Metal

### ISSUE THREAD

**Issue by alice-sowerby** [c0dyhi11/packet-router#16]
![image](https://user-images.githubusercontent.com/17722440/151051973-f8a20c61-7658-4355-9e01-95d1f56064f0.png)

**Comment by jacobsmith928** [comment]
Howdy, bumping this one!

**Comment by displague** [comment]
This was missed in https://github.com/equinix-labs/terraform-metal-vyos-router/pull/11 and https://github.com/equinix-labs/terraform-metal-vyos-router/pull/19

The repo description has now been renamed per the issue description.
